export const InvarianceVotingAbi = [
  {
    type: 'function',
    name: 'createProposal',
    inputs: [
      { name: 'proposalId', type: 'bytes32' },
      { name: 'identityId', type: 'bytes32' },
      { name: 'title', type: 'string' },
      { name: 'descriptionHash', type: 'bytes32' },
      { name: 'votingPeriod', type: 'uint256' },
      { name: 'quorum', type: 'uint256' },
      { name: 'threshold', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settleVotes',
    inputs: [
      { name: 'proposalId', type: 'bytes32' },
      { name: 'merkleRoot', type: 'bytes32' },
      { name: 'totalFor', type: 'uint256' },
      { name: 'totalAgainst', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'verifyVote',
    inputs: [
      { name: 'proposalId', type: 'bytes32' },
      { name: 'voter', type: 'address' },
      { name: 'support', type: 'bool' },
      { name: 'weight', type: 'uint256' },
      { name: 'proof', type: 'bytes32[]' },
    ],
    outputs: [{ name: 'valid', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'didPass',
    inputs: [{ name: 'proposalId', type: 'bytes32' }],
    outputs: [{ name: 'passed', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposal',
    inputs: [{ name: 'proposalId', type: 'bytes32' }],
    outputs: [
      {
        name: 'proposal',
        type: 'tuple',
        components: [
          { name: 'identityId', type: 'bytes32' },
          { name: 'title', type: 'string' },
          { name: 'descriptionHash', type: 'bytes32' },
          { name: 'votingPeriod', type: 'uint256' },
          { name: 'quorum', type: 'uint256' },
          { name: 'threshold', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'merkleRoot', type: 'bytes32' },
          { name: 'totalFor', type: 'uint256' },
          { name: 'totalAgainst', type: 'uint256' },
          { name: 'settled', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ProposalCreated',
    inputs: [
      { name: 'proposalId', type: 'bytes32', indexed: true },
      { name: 'identityId', type: 'bytes32', indexed: true },
      { name: 'title', type: 'string', indexed: false },
      { name: 'votingPeriod', type: 'uint256', indexed: false },
      { name: 'quorum', type: 'uint256', indexed: false },
      { name: 'threshold', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'VotesSettled',
    inputs: [
      { name: 'proposalId', type: 'bytes32', indexed: true },
      { name: 'merkleRoot', type: 'bytes32', indexed: false },
      { name: 'totalFor', type: 'uint256', indexed: false },
      { name: 'totalAgainst', type: 'uint256', indexed: false },
    ],
  },
] as const;
